### ISSUE TITLE
Create Tinkerbell PoC

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/machine-controller#909] opened 2021-03-02 13:33 UTC
**User Story**
In order to understand if we can use tinkerbell for bare metal provisioning we should create a small bare metal cluster and check Tinkerbell provisioning and API capabilities.

**Acceptance criteria**
* Having tinkerbell installation that works and expose API that can be reached by machine-controller

**Comment by mfranczy** [comment] 2021-03-02 13:35
**User Story**
In order to understand if we can use tinkerbell for bare metal provisioning we should create a small bare metal cluster and check Tinkerbell provisioning and API capabilities.

**Acceptance criteria**
* Having tinkerbell installation that works and expose API that can be reached by machine-controller

**Comment by moadqassem** [comment] 2021-03-09 09:01
This issue is actually a duplicate of this one:
https://github.com/kubermatic/machine-controller/issues/908

**Closed by moadqassem** 2021-03-09 09:01 UTC
