### ISSUE TITLE
Improve preemptible GCE workers

### ISSUE THREAD

**Issue by toschneck** [kubermatic/machine-controller#1551] opened 2023-02-02 13:30 UTC
Currently the preemptible support on GCE is kind of instable from the view of the users. Somehow preemptible machines stops and will be stay longer time as node `NotReady` in side of the cluster, what cause instability. 
E.g. right now in our run-2 environment.

![VM instances – Compute Engine – kubermatic-run – Google Cloud console 2023-02-02 14-19-22](https://user-images.githubusercontent.com/4659261/216335903-939c011f-d169-49bf-9ecc-dea9c50116e6.png)
![minimize-to-maximize 2023-02-02 14-20-14](https://user-images.githubusercontent.com/4659261/216336014-8c1aad98-3f7d-4808-bf99-00d955b83a89.png)

# Ideas to improve
- delete stopped machine and let machinedeployment create a new one, if preemtible node reach "terminated status"

**Comment by toschneck** [comment] 2023-02-02 23:05
Temporary workaround is a own job https://github.com/kubermatic/sig-cs-infra/commit/3d297e9d7d85c946c6dbb8d6ec80fa4fdb28999a

**Comment by kron4eg** [comment] 2023-02-22 16:27
This behavior is by design of preemptive VMs. However there is a light in the end of the tunnel, GCE offers new [Spot VMs](https://cloud.google.com/compute/docs/instances/spot), they are just like Preemptive VMs but better in the sense that DELETE action can be specified for `InstanceTerminationAction` field of the VM creation API.

I'll close this issue in favor of #1573, as preemptive VMs are deprecated anyway.

**Comment by kron4eg** [comment] 2023-02-22 16:27
@csengerszabo it's not a bug it's a feature (of the platform) :joy:

**Closed by kron4eg** 2023-02-22 16:27 UTC
Labels: kind/bug, sig/cluster-management
