### ISSUE TITLE
Azure VM rotation leave unassigned NiC & Volumes 

### ISSUE THREAD

**Issue by mfahlandt** [kubermatic/machine-controller#1356] opened 2022-07-13 13:14 UTC
The Rotation of nodes or deletion of nodes sometimes leave NiC and Volumes unattached. 

Also, the nodes are sometimes not disappearing out of the node list in the cluster, because the finalizer does not finish. 

It appears the VM is removed by Azure but then the machine controller finalizers are failing because the NiC and the disc are no longer related to the already deleted VM.

According to Microsoft you can add an option to delete the VM always with nic and volume. 

Dead Nodes with broken finalizer: 

![Bildschirmfoto-20220420105158-1403x702](https://user-images.githubusercontent.com/5739844/178740917-f2d8e620-5817-4ae5-a1a3-4837be0b0180.png)
![Bildschirmfoto-20220420105511-907x288](https://user-images.githubusercontent.com/5739844/178740923-a327fed3-19d6-4603-b414-9fdd64015a2d.png)

Unassigned Discs & Nics in Azure
![disc](https://user-images.githubusercontent.com/5739844/178741973-75d20258-a5ab-4f95-a073-e757e784514d.png)
![nic](https://user-images.githubusercontent.com/5739844/178741976-f0d7e1ea-41ad-4607-a34d-8dda1dfa58ea.png)

What should happen, machines should be removed without any nics and volumes left behind.

**Comment by ahmedwaleedmalik** [comment] 2022-07-19 09:51
@mfahlandt which KKP version did you face this issue on?

**Comment by ahmedwaleedmalik** [comment] 2022-07-22 08:22
We tried fixing this with https://github.com/kubermatic/machine-controller/pull/1286 but that PR was never back-ported. So it's highly likely that this issue is not there in the latest master.

**Comment by shatoboar** [comment] 2022-07-29 07:49
@mfahlandt The issue isn't reproducable on my end, so I will close the issue for now and port back #1286 to earlier versions. 
If this issue persists, please reopen the issue.

**Closed by shatoboar** 2022-07-29 07:49 UTC
Labels: kind/bug, kind/cleanup, sig/cluster-management

**Comment by embik** [comment] 2022-08-04 09:35
@shatoboar I think this issue still persists, check out resource group `kubernetes-xbhhw5bqxz` in our Azure subscription for example. There's a NIC leftover in there.

**Comment by mfahlandt** [comment] 2022-08-04 09:37
I tested it with 2.19 multiple versions.

**Comment by embik** [comment] 2022-08-04 09:43
re:

> It appears the VM is removed by Azure but then the machine controller finalizers are failing because the NiC and the disc are no longer related to the already deleted VM.

I don't think that is the problem because both NICs and public IPs are identified as "related" via tags on those resources. So the VM not existing anymore should not impact MC's ability to identify those resources as related.

**Comment by ahmedwaleedmalik** [comment] 2022-08-04 09:45
So in 2.19 the fix was never backported. But for 2.20 and master we were not able to reproduce this issue. 

The issue mainly is from KKP side and not from MC. So it'll probably be converted in another ticket for KKP. That's my opinion.

**Comment by mfahlandt** [comment] 2022-08-04 09:50
> re:
> 
> > It appears the VM is removed by Azure but then the machine controller finalizers are failing because the NiC and the disc are no longer related to the already deleted VM.
> 
> I don't think that is the problem because both NICs and public IPs are identified as "related" via tags on those resources. So the VM not existing anymore should not impact MC's ability to identify those resources as related.

This is the funny part. When you take a look at the screenshot Azure removes the relation from the NiC and the Disc. Idk if that is happening because we remove the vm but usually the leftovers have no relation anymore. This then might also be the reason why the finalizers fail, because it can not find the vm anymore.

**Comment by embik** [comment] 2022-08-04 09:58
@mfahlandt but that's what I mean, the attachment that Azure creates is not used to identify the resources that need deletion. It's done via a custom tag that MC adds to all resources belonging to a specific `Machine`. So attachments should play no role.

**Comment by ahmedwaleedmalik** [comment] 2022-08-04 10:03
@embik @mfahlandt I'll highly recommend that let's open up a dedicated ticket for KKP; fix azure cleanup. And then let's investigate it by following the complete lifecycle for a cluster.

**Comment by mfahlandt** [comment] 2022-08-04 10:12
@ahmedwaleedmalik agreed
